export const toneOptions = [
  { label: "Formal", value: "formal" },
  { label: "Informal", value: "informal" },
  { label: "Authoritative", value: "authoritative" },
  { label: "Friendly", value: "friendly" },
  { label: "Confident", value: "confident" },
  { label: "Sincere", value: "sincere" },
  { label: "Humorous", value: "humorous" },
  { label: "Serious", value: "serious" },
  { label: "Professional", value: "professional" },
  { label: "Motivational", value: "motivational" },
  { label: "Passionate", value: "passionate" },
  { label: "Relaxed", value: "relaxed" },
  { label: "Reliable", value: "reliable" },
  { label: "Respectful", value: "respectful" },
  { label: "Sarcastic", value: "sarcastic" },
  { label: "Witty", value: "witty" },
  { label: "Youthful", value: "youthful" },
  { label: "Custom", value: "custom" },
];
